import { loadGLTF, Geometry } from "../engine/index.js";

/**
 * NIGHT MARKET — 3D assets. Every model is a .glb in assets/models, generated by tools/make-models.mjs
 * and read with the engine's glTF loader.
 * @module game/assets
 */

const STALL_TYPES = ["skewers", "dumplings", "noodles", "takoyaki", "tea", "rival"];

/**
 * Load everything the scene needs. Resolves to:
 *   person, dog   glTF assets with a skeleton and animation clips
 *   stalls        { skewers, dumplings, noodles, takoyaki, tea, rival }: assets with "body", "level2", "level3" meshes
 *   props         one asset holding the street furniture and the food people carry
 *   upright       quaternion that stands a loaded model up in the engine's Z-up world
 *   personGeometry(hairStyle, prop)   merged, cached geometry for one combination of hair and accessory
 * @param {string} [base] folder holding the .glb files
 */
export async function loadAssets(base = "assets/models/") {
    const names = ["person", "dog", "props", ...STALL_TYPES.map((t) => "stall_" + t)];
    const loaded = await Promise.all(names.map((n) => loadGLTF(base + n + ".glb")));
    const byName = Object.fromEntries(names.map((n, i) => [n, loaded[i]]));
    const person = byName.person, variants = new Map();
    return {
        person, dog: byName.dog, props: byName.props, upright: person.upright,
        stalls: Object.fromEntries(STALL_TYPES.map((t) => [t, byName["stall_" + t]])),
        /** One mesh per look: the body plus the chosen hair and accessory, so a person is a single draw call. */
        personGeometry(hairStyle, prop) {
            const key = hairStyle + "|" + (prop || "");
            let g = variants.get(key);
            if (!g) {
                const parts = [person.geometry("body")];
                // hats replace the hair on top; long hair still shows below them
                if (prop === "tophat" || prop === "cap") { if (hairStyle === 2) parts.push(person.geometry("hair2")); }
                else parts.push(person.geometry("hair" + hairStyle));
                if (prop && person.geometry(prop)) parts.push(person.geometry(prop));
                g = Geometry.merge(parts.map((geometry) => ({ geometry })), { name: "person-" + key, skin: true });
                variants.set(key, g);
            }
            return g;
        },
    };
}
